apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzapayment
  labels:
    app: pizzapayment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzapayment
  template:
    metadata:
      labels:
        app: pizzapayment
    spec:
      containers:
        - name: pizzapayment
          image: username/pizzapayment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5